services:
  app:
    container_name: app-container
    build:
      context: .
    volumes:
      - ./books_app:/work
      - /work/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - ${APP_PORT}:3000
      - ${STUDIO_PORT}:5555
    networks:
      - default-network
  db:
    image: postgres:15
    container_name: db-container
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - default-network

volumes:
  db_data:
  
networks:
  default-network:
    external: true