services:
  app:
    container_name: app-container
    build:
      context: .
    volumes:
      - ./sns_app:/work
    ports:
      - ${APP_PORT}:3000
      - ${STUDIO_PORT}:5555
    #environment:
      #DATABASE_URL: mysql://${DB_USER}:${MYSQL_PASSWORD}@db3306:
      #DATABASE_URL="mysql://dev:dev2025@db:3306/sns-db"
    networks:
      - default-network
  db:
    image: mysql:8
    container_name: db-container
    environment: 
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:3306
    #command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./database/initialize:/docker-entrypoint-initdb.d
      - ./database/config/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - default-network

networks:
  default-network:
    external: true