version: "3.9"

services:
  app:
    env_file:
      - .env.production
    command: sh -c "npm ci && npm run build && npm run start -H 0.0.0.0"
    ports:
      - ${APP_PORT}:3000
      - ${STUDIO_PORT}:5555

  db:
    image: postgres:15
    env_file:
      - .env.production
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql
